In [42]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
import webbrowser
from sklearn.decomposition import PCA
from sklearn.metrics.pairwise import paired_cosine_distances as pcd
import time as t

In [43]:
yoox=pd.read_csv('yoox_final.csv').drop('Unnamed: 0',axis=1)
yoox.drop_duplicates(keep='first',inplace=True)

In [44]:
yoox.head()

brand                                 url  price_actual  \
0         8 by YOOX  http://yoox.com/fr/41925191HP/item         249.0   
1             MARNI  http://yoox.com/fr/14007863DH/item         218.0   
2             MARNI  http://yoox.com/fr/35421773RV/item         421.0   
3         8 by YOOX  http://yoox.com/fr/13381785CM/item         119.0   
4  STELLA McCARTNEY  http://yoox.com/fr/41796284SB/item         257.0   

   size_30  size_32  size_34  size_36  size_38  size_40  size_42  ...  \
0        0        0        1        1        1        1        1  ...   
1        0        0        0        1        0        0        0  ...   
2        0        0        1        1        1        0        1  ...   
3        0        0        1        1        1        1        1  ...   
4        1        1        0        0        0        0        0  ...   

   colors_Vert acide  colors_Vert clair  colors_Vert foncé  \
0                  0                  0                  0   
1                  0                  0                  0   
2                  0                  0                  0   
3                  0                  0                  0   
4                  0                  0                  0   

   colors_Vert militaire  colors_Vert pétrole  colors_Vert émeraude  \
0                      0                    0                     0   
1                      0                    0                     0   
2                      0                    0                     0   
3                      0                    0                     0   
4                      0                    0                     0   

   colors_Vieux rose  colors_Violet  colors_Violet clair  colors_Violet foncé  
0                  0              0                    0                    0  
1                  0              0                    0                    0  
2                  0              0                    0                    0  
3                  0              0                    0                    0  
4                  0              0                    0                    0  

[5 rows x 114 columns]

In [45]:
yoox_ml = yoox.drop(["brand", "url","price_actual","discount_rate",'compositions','item'], axis=1)
yoox_ml[[ '_Blouses', '_Bodycon Dress', '_Bomber Jackets', '_Cardigans', '_Coats', '_Culottes', '_Denim Pants', '_Down-coat',
 '_Hoodies', '_Jackets', '_Jumpers', '_Jumpsuits', '_Knee Length Skirt', '_Long Coats', '_Maxi Dress', '_Maxi Skirt',
         '_Midi Dress', '_Midi Skirt', '_Mini Dress', '_Mini Skirt', '_One piece Swimsuit', '_Pyjamas', '_Shirts',
 '_Shortµs', '_T-shirts', '_Tops', '_Trench Coats', '_Trousers', '_Turtle Necks']]=yoox_ml[[ '_Blouses', '_Bodycon Dress', '_Bomber Jackets', '_Cardigans', '_Coats', '_Culottes', '_Denim Pants', '_Down-coat',
 '_Hoodies', '_Jackets', '_Jumpers', '_Jumpsuits', '_Knee Length Skirt', '_Long Coats', '_Maxi Dress', '_Maxi Skirt',
         '_Midi Dress', '_Midi Skirt', '_Mini Dress', '_Mini Skirt', '_One piece Swimsuit', '_Pyjamas', '_Shirts',
 '_Shorts', '_T-shirts', '_Tops', '_Trench Coats', '_Trousers', '_Turtle Necks']].apply(lambda x: x*1.5)

In [46]:
yoox_ml[[  'size_30','size_32', 'size_34', 'size_36', 'size_38', 'size_40', 'size_42', 'size_44', 'size_46', 'size_48']]=yoox_ml[['size_30',
 'size_32', 'size_34', 'size_36', 'size_38', 'size_40', 'size_42', 'size_44', 'size_46', 'size_48',]].apply(lambda x: x*0.7)

In [47]:
yoox_ml[['colors_Anthracite', 'colors_Argent', 'colors_Aubergine', 'colors_Beige', 'colors_Blanc', 'colors_Bleu', 'colors_Bleu ciel',
 "colors_Bleu d'azur", 'colors_Bleu foncé', 'colors_Bleu pétrole', 'colors_Bleu électrique', 'colors_Bleu-gris', 'colors_Bordeaux',
 'colors_Brique', 'colors_Camel', 'colors_Chair', 'colors_Chocolat', 'colors_Corail', 'colors_Cuivre', 'colors_Fuchsia',
 'colors_Gris', 'colors_Gris clair', 'colors_Gris tourterelle', 'colors_Ivoire', 'colors_Jaune', 'colors_Jaune clair', 'colors_Kaki',
 'colors_Marron', 'colors_Mauve', 'colors_Moka', 'colors_Noir', 'colors_Noisette', 'colors_Ocre', 'colors_Or', 'colors_Orange',
 'colors_Platine', 'colors_Plomb', 'colors_Pourpre', 'colors_Rose', 'colors_Rose clair', 'colors_Rouge', 'colors_Rouille',
 'colors_Sable', 'colors_Saumon', 'colors_Turquoise', 'colors_Vert', 'colors_Vert acide', 'colors_Vert clair', 'colors_Vert foncé',
 'colors_Vert militaire', 'colors_Vert pétrole', 'colors_Vert émeraude', 'colors_Vieux rose', 'colors_Violet', 'colors_Violet clair',
 'colors_Violet foncé']]=yoox_ml[['colors_Anthracite', 'colors_Argent', 'colors_Aubergine', 'colors_Beige', 'colors_Blanc', 'colors_Bleu', 'colors_Bleu ciel',
 "colors_Bleu d'azur", 'colors_Bleu foncé', 'colors_Bleu pétrole', 'colors_Bleu électrique', 'colors_Bleu-gris', 'colors_Bordeaux',
 'colors_Brique', 'colors_Camel', 'colors_Chair', 'colors_Chocolat', 'colors_Corail', 'colors_Cuivre', 'colors_Fuchsia',
 'colors_Gris', 'colors_Gris clair', 'colors_Gris tourterelle', 'colors_Ivoire', 'colors_Jaune', 'colors_Jaune clair', 'colors_Kaki',
 'colors_Marron', 'colors_Mauve', 'colors_Moka', 'colors_Noir', 'colors_Noisette', 'colors_Ocre', 'colors_Or', 'colors_Orange',
 'colors_Platine', 'colors_Plomb', 'colors_Pourpre', 'colors_Rose', 'colors_Rose clair', 'colors_Rouge', 'colors_Rouille',
 'colors_Sable', 'colors_Saumon', 'colors_Turquoise', 'colors_Vert', 'colors_Vert acide', 'colors_Vert clair', 'colors_Vert foncé',
 'colors_Vert militaire', 'colors_Vert pétrole', 'colors_Vert émeraude', 'colors_Vieux rose', 'colors_Violet', 'colors_Violet clair',
 'colors_Violet foncé']].apply(lambda x: x*1.3)

In [64]:
g=input(f"Choose a Product\nHere is a suggestion{str(yoox.sample()['item'].unique())}\n")
t.sleep(1)
# ☺

Choose a Product
Here is a suggestion['13388817KR']
13388817KR


In [65]:
i_d0=yoox[yoox.item==g].index
webbrowser.open(f'http://yoox.com/fr/{g}/item')
t.sleep(8)

In [66]:
pca=PCA(0.99)
pca.fit(yoox_ml)
pca.n_components_

86

In [67]:
yoox_ml_new=pca.transform(yoox_ml)

In [68]:
cosine = [1 - pcd(yoox_ml_new[i_d0].reshape(-1, 1).T, i.reshape(-1, 1).T) for i in yoox_ml_new]
results=cosine.copy()
results.sort(reverse=True)
results=[i for i in results if i > 0.78]
indices = [i for i, x in enumerate(cosine) if x in results[1:]]
urls=[]
for i in indices:
    urls.append(yoox.url[i])
new_urls=yoox[(yoox['url'].isin(urls))==True].sort_values(by='price_actual')['url'].drop_duplicates(keep='first').head(4).tolist()
for i in new_urls:
    webbrowser.open(i)

In [69]:
results

[array([1.]),
 array([0.93607133]),
 array([0.93564779]),
 array([0.89056836]),
 array([0.8862675]),
 array([0.88003692]),
 array([0.87809564]),
 array([0.87621079]),
 array([0.85351451]),
 array([0.81253804])]

In [30]:
yoox_ml_new[i_d0].shape

(1, 82)

In [38]:
1-pcd(yoox_ml_new[i_d0].reshape(-1, 1).T,yoox_ml_new[i_d0].reshape(-1, 1).T)

array([1.])

In [42]:
results

[array([1.]), array([0.99990076]), array([0.85746848]), array([0.84896879])]

In [44]:
indices

[308, 1540, 2932, 4387]

In [46]:
yoox[(yoox['url'].isin(urls))==True]['url']

1540    http://yoox.com/fr/13257350GG/item
2932    http://yoox.com/fr/13216935SC/item
4387    http://yoox.com/fr/13118384RN/item
Name: url, dtype: object